# --------------
# Configuration
# --------------
import pandas as pd
from pathlib import Path

configfile: "workflow/config.yaml"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"

# Rules
rule pheno_step1:
    input:
        code_lists=expand(config["dir_codelist"] + "{pheno}.tsv",
                          pheno = [k for k,v in config["step1_pheno"].items()]),
        hesin_diag = config["dir_data"] + config["data_spec"]["hesin_diag"]["filename"],
        hesin_oper = config["dir_data"] + config["data_spec"]["hesin_oper"]["filename"],
        death_cause = config["dir_data"] + config["data_spec"]["death_cause"]["filename"]
    output:
        config["dir_results"] + "pheno_step1.tsv"
    script:
        "scripts/pheno_step1.R"
