dir_data: "resources/data/"
dir_codelist: "resources/code_list/"
dir_results: "results/"
file_pheno: "2021-05_ukb_hf_pheno_HES_oct_2020.txt"

data_spec:
  hesin_diag:
    filename: "hesin_diag.txt"
    col_eid: "eid"
    col_icd10: "diag_icd10"
    col_icd9: "diag_icd9"

  death_cause:
    filename: "death_cause.txt"
    col_eid: "eid"
    col_icd10: "cause_icd10"

  hesin_oper:
    filename: "hesin_oper.txt"
    col_eid: "eid"
    col_opcs4: "oper4"

  lvef:
    filename: "lvef_derived.txt"
    col_eid: "eid_58356"
    col_lvef: "LVEF"

step1_pheno_data:
  AF: "ALL"
  HF: ["hesin_diag", "hesin_oper"]
  valveHD: "ALL"
  congHD: "ALL"
  LVSD: "ALL"
  MI: "ALL"
